FROM golang:1.16-alpine

WORKDIR /usr/src/app

RUN apk add --update make
RUN go install github.com/cespare/reflex@latest

COPY go.mod go.sum ./
RUN go mod download

ENV "ENV" "development"
CMD ["make", "watch"]
